### ISSUE TITLE
KMS encryption context not backwards compatible

### ISSUE THREAD

**Issue by sami9gag** [mozilla/sops#190]
In SOPS 2.0 KMS encryption context is stored as a string value in the json output where the old python version used JSON Object to store encryption context.

```sh
❯ jq '.sops.kms | .[].context' encrypted-python
{
  "a": "b",
  "c": "d"
}
❯ jq '.sops.kms | .[].context' encrypted-go
"a:b,c:d"
```

The two outputs are incompatible with each other and reading an old SOPS encrypted file with SOPS 2.0 will cause a stack trace.

```
panic: interface conversion: interface is map[string]interface {}, not string [recovered]
	panic: interface conversion: interface is map[string]interface {}, not string

goroutine 1 [running]:
panic(0x46e220, 0xc420077b40)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.HandleAction.func1(0xc42012f7a8)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:473 +0x29e
panic(0x46e220, 0xc420077b40)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:458 +0x243
go.mozilla.org/sops/json.Store.kmsEntries(0xc420158120, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/json/store.go:316 +0x656
go.mozilla.org/sops/json.Store.UnmarshalMetadata(0xc420121400, 0x740, 0x940, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/json/store.go:279 +0x8f5
go.mozilla.org/sops/json.BinaryStore.UnmarshalMetadata(0xc420121400, 0x740, 0x940, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/json/store.go:61 +0x7c
go.mozilla.org/sops/json.(*BinaryStore).UnmarshalMetadata(0x7397c8, 0xc420121400, 0x740, 0x940, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:21 +0xb0
main.loadEncryptedFile(0xc4200b6dc0, 0x6fd380, 0x7397c8, 0xc420121400, 0x740, 0x940, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/cmd/sops/main.go:74 +0xa1
main.main.func1(0xc4200b6dc0, 0x0, 0x0)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/cmd/sops/main.go:227 +0x322
reflect.Value.call(0x44f060, 0x51eaa8, 0x13, 0x4de77e, 0x4, 0xc42012f768, 0x1, 0x1, 0xfe068, 0x4d3800, ...)
	/usr/local/Cellar/go/1.7.4/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x44f060, 0x51eaa8, 0x13, 0xc42012f768, 0x1, 0x1, 0x51e9e8, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/reflect/value.go:302 +0xa4
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x44f060, 0x51eaa8, 0xc4200b6dc0, 0x0, 0x0)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:482 +0x1e0
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420134000, 0xc42007c090, 0x3, 0x3, 0x0, 0x0)
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:240 +0x596
main.main()
	/Users/samihaahtinen/sources/go/src/go.mozilla.org/sops/cmd/sops/main.go:284 +0xe0e
```

**Comment by autrilla** [comment]
Thanks for the bug report. This should be easy to fix by checking whether `entry["context"]` is a `map[string]string` [here](https://github.com/mozilla/sops/blob/master/json/store.go#L316) and entirely bypassing `kms.ParseKMSContext`.

Are you interested on contributing a patch for this issue?

**Comment by sami9gag** [comment]
I can take a look, although my Go skills are extremely limited. I think the question that warrants discussion here is how to fix the current output. The output should be incompatible with the current python version as well, so should we change the output or just fix the parsing?

I haven't tested 2.0 generated file with an older SOPS, so this is based on assumptions.

**Comment by autrilla** [comment]
I think we should change the output [here](https://github.com/mozilla/sops/blob/master/kms/keysource.go#L169-L174) to be the same as the old Python version (using a `map[string]string` instead of a comma separated string), but then also allow the parsing to use both formats, so that documents using encryption contexts with versions of sops previous to this fix can still be decoded after the fix.
