### ISSUE TITLE
panic when YAML has no MAC

### ISSUE THREAD

**Issue by jbuck** [mozilla/sops#195]
Similar to #194 except it crashed on the shared git files.

panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x49a160, 0xc420338140)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
go.mozilla.org/sops/yaml.(*Store).UnmarshalMetadata(0x785f68, 0xc42015c000, 0xb58, 0xd58, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jbuckley/Documents/go/src/go.mozilla.org/sops/yaml/store.go:159 +0x3c1
main.loadEncryptedFile(0xc420095180, 0x749620, 0x785f68, 0xc42015c000, 0xb58, 0xd58, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jbuckley/Documents/go/src/go.mozilla.org/sops/cmd/sops/main.go:74 +0xa1
main.main.func1(0xc420095180, 0x0, 0x0)
	/Users/jbuckley/Documents/go/src/go.mozilla.org/sops/cmd/sops/main.go:227 +0x383
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x47aae0, 0x55bb90, 0xc420095180, 0x0, 0x0)
	/Users/jbuckley/Documents/go/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:485 +0xd4
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420105d40, 0xc42000c1e0, 0x3, 0x3, 0x0, 0x0)
	/Users/jbuckley/Documents/go/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:259 +0x74f
main.main()
	/Users/jbuckley/Documents/go/src/go.mozilla.org/sops/cmd/sops/main.go:284 +0xe14

**Comment by jbuck** [comment]
Update: @autrilla and I found that this error occurs when the YAML file has no MAC in the `sops` key
