### ISSUE TITLE
Errors in output when running `sops example.yaml`

### ISSUE THREAD

**Issue by petemoore** [mozilla/sops#32]
When following the project `README.rst` step by step, I got the following output when running `sops example.yaml`. Maybe this is expected, but wasn't explicitly stated in the README. I can confirm it successfully opened the file in an editor with the secrets decrypted.

Thanks!

```
(sops)pmoore@Petes-iMac:~/git/sops master $ sops example.yaml
[warning] skipping kms arn:aws:kms:us-east-1:656532927350:key/920aff2e-c5f1-4040-943a-047fa387b27e: An error occurred (AccessDeniedException) when calling the Decrypt operation: The ciphertext references a key that either does not exist or you do not have access to. 
[warning] skipping kms arn:aws:kms:ap-southeast-1:656532927350:key/9006a8aa-0fa6-4c14-930e-a2dfb916de1d: An error occurred (AccessDeniedException) when calling the Decrypt operation: The ciphertext references a key that either does not exist or you do not have access to. 
gpg: encrypted with 1024-bit RSA key, ID 7CD79CC0, created 2015-10-08
      "SOPS Functional Tests (https://github.com/mozilla/sops/) <ulfr+sopstests@mozilla.com>"
temp file created at /var/folders/v9/mll6p_rj5h94dt_m5m8j0f9c0000gn/T/tmpF6qNM1.yaml
file written to example.yaml
```

**Comment by petemoore** [comment]
Continuing further I get more problems:

```
pmoore@Petes-iMac:~/git/sops master $ export SOPS_PGP_FP=85EE8DBDAFB5CBAD273A33518295FE77B475FEBC
pmoore@Petes-iMac:~/git/sops master $ sops test-file.yaml
Traceback (most recent call last):
  File "/Users/pmoore/venvs/sops/bin/sops", line 11, in <module>
    sys.exit(main())
  File "/Users/pmoore/venvs/sops/lib/python2.7/site-packages/sops/__init__.py", line 193, in main
    if len(args.add_kms) > 0 or len(args.add_pgp) > 0 \
TypeError: object of type 'NoneType' has no len()
pmoore@Petes-iMac:~/git/sops master $ 
```

Many thanks!

**Comment by jvehent** [comment]
Fixed in https://github.com/mozilla/sops/commit/255eed294de22cf5506911df690dffd2cc35b035
Thanks a lot for reporting the issue! :+1:
