### ISSUE TITLE
example set value results in stack trace

### ISSUE THREAD

**Issue by MansM** [mozilla/sops#461]
sops --set '["app2"]["key"] "app2keystringvalue"' existingfile.yml
```
anic: interface conversion: interface {} is string, not sops.TreeBranches

goroutine 1 [running]:
main.jsonValueToTreeInsertableValue(0x7ffeefbff763, 0x14, 0x190ec78, 0x1, 0x7ffeefbff753, 0xf)
	/private/tmp/sops-20190418-13511-18dvxtu/sops-3.3.0/src/go.mozilla.org/sops/cmd/sops/main.go:863 +0x35a
main.extractSetArguments(0x7ffeefbff753, 0x24, 0xc0000c28a0, 0x7ffeefbff753, 0x24, 0x0, 0x0, 0x1aacac0, 0x176ca8e)
	/private/tmp/sops-20190418-13511-18dvxtu/sops-3.3.0/src/go.mozilla.org/sops/cmd/sops/main.go:875 +0xd6
main.main.func5(0xc000176580, 0x0, 0x0)
	/private/tmp/sops-20190418-13511-18dvxtu/sops-3.3.0/src/go.mozilla.org/sops/cmd/sops/main.go:564 +0x231d
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x17f8040, 0x1947068, 0xc000176580, 0x0, 0x0)
	/private/tmp/sops-20190418-13511-18dvxtu/sops-3.3.0/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
go.mozilla.org/sops/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000200ea0, 0xc0000c8000, 0x4, 0x4, 0x0, 0x0)
	/private/tmp/sops-20190418-13511-18dvxtu/sops-3.3.0/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x590
main.main()
	/private/tmp/sops-20190418-13511-18dvxtu/sops-3.3.0/src/go.mozilla.org/sops/cmd/sops/main.go:649 +0x2578
```
```
OS: macOS high sierra
sops -v
sops 3.3.0

brew info sops
sops: stable 3.3.0 (bottled), HEAD
Editor of encrypted files
https://github.com/mozilla/sops
/usr/local/Cellar/sops/3.3.0 (5 files, 22MB) *
  Poured from bottle on 2019-04-30 at 17:40:11
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/sops.rb

```

**Comment by thepont** [comment]
This bug is also occurring on Linux sops 3.3.0 (using the Arch linux AUR sops package https://aur.archlinux.org/packages/sops/).

Does not seem to happen on version 3.2.0 on OSX.
