### ISSUE TITLE
Go panic, not able to decrypt anymore

### ISSUE THREAD

**Issue by dpsi** [mozilla/sops#588]
I am suddenly not able to decrypt a file anymore. I am not sure what the issue is. Here is the stacktrace:
```
sops -d -i spigot2.yml
panic: interface conversion: interface {} is int, not string

goroutine 1 [running]:
go.mozilla.org/sops/v3.Tree.Decrypt.func1.1(0xe46d80, 0xc0003c6000, 0xc0003bc030, 0x1, 0x1, 0xc00025a0c0, 0xc00025a0b0, 0x44530e, 0xc0003bc030)
        /home/ajvb/gocode/src/go.mozilla.org/sops/sops.go:415 +0x895
go.mozilla.org/sops/v3.TreeBranch.walkValue(0xc000103500, 0x7, 0x8, 0xe46d80, 0xc00035c1d0, 0xc0003bc030, 0x1, 0x1, 0xc00025a240, 0x418f0e, ...)
        /home/ajvb/gocode/src/go.mozilla.org/sops/sops.go:225 +0x7a3
go.mozilla.org/sops/v3.TreeBranch.walkBranch(0xc000103500, 0x7, 0x8, 0xc000103500, 0x7, 0x8, 0x190eba8, 0x0, 0x0, 0xc00025a240, ...)
        /home/ajvb/gocode/src/go.mozilla.org/sops/sops.go:278 +0x423
go.mozilla.org/sops/v3.Tree.Decrypt.func1(0xc000103500, 0x7, 0x8, 0x1, 0x1)
        /home/ajvb/gocode/src/go.mozilla.org/sops/sops.go:370 +0x195
go.mozilla.org/sops/v3.Tree.Decrypt(0x0, 0xed56d23eb, 0x0, 0xc00035ca50, 0xc, 0x0, 0x0, 0x0, 0x0, 0xc000276360, ...)
        /home/ajvb/gocode/src/go.mozilla.org/sops/sops.go:436 +0x1f7
go.mozilla.org/sops/v3/cmd/sops/common.DecryptTree(0xc000305380, 0xc000344300, 0x1, 0x1, 0x0, 0x1211f80, 0xc000301b00, 0xc000344300, 0x1, 0x1, ...)
        /home/ajvb/gocode/src/go.mozilla.org/sops/cmd/sops/common/common.go:87 +0x1ec
main.decrypt(0x1211f80, 0xc000301b00, 0x7f57acf28408, 0x190eba8, 0x7f57acf28408, 0x190eba8, 0xc0001368c0, 0x36, 0x0, 0x0, ...)
        /home/ajvb/gocode/src/go.mozilla.org/sops/cmd/sops/decrypt.go:34 +0x1f9
main.main.func8(0xc0000b2dc0, 0x0, 0x0)
        /home/ajvb/gocode/src/go.mozilla.org/sops/cmd/sops/main.go:675 +0x2b06
gopkg.in/urfave/cli%2ev1.HandleAction(0xe62ca0, 0x10603e0, 0xc0000b2dc0, 0x0, 0x0)
        /home/ajvb/gocode/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0002b7a00, 0xc0000c0000, 0x4, 0x4, 0x0, 0x0)
        /home/ajvb/gocode/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x58c
main.main()
        /home/ajvb/gocode/src/go.mozilla.org/sops/cmd/sops/main.go:823 +0x2de4
```

This is a yaml file encrypted with pgp.

sops 3.5.0 (latest)
Ubuntu 18.04.3 LTS amd64

Feel free to message me privately if you would like the yaml file and PGP key.

**Comment by dpsi** [comment]
I tried downgrading to 3.4 (version file was created under) and still the same panic.

Yaml file passes validator.

**Comment by ajvb** [comment]
@dpsi Feel free to email a version of the yaml file encrypted with my key: https://gpg.mozilla.org/pks/lookup?search=++++0xF69E4901EDBAD2D1753F8C67A64535C4163FB307&op=vindex

Can retrieve my key with:
```
gpg --keyserver gpg.mozilla.org --recv-keys 0xF69E4901EDBAD2D1753F8C67A64535C4163FB307
```

My email is my github user name `@mozilla.com` (or the one in the key).

To encrypt with sops you can do: `sops -e --pgp F69E4901EDBAD2D1753F8C67A64535C4163FB307 <file>`

**Comment by dpsi** [comment]
Hi @ajvb, sorry for the delayed response. Exam season just wrapped up for myself.

It appears this was caused by the end-application adding unencrypted data to the already encrypted yaml. I was able to decrypt it after editing the file, so there is no urgency or concern for loss of data.

In any case I believe this may be a bug or at minimum, poor UX. I will try to send you both the unencrypted and encrypted versions this week. 

Thanks
