### ISSUE TITLE
Traceback:  AttributeError: 'EntryPoint' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by rpappalax** [mozilla/sops#67]
I've tried decrypting a file using both sops version 1.10 (latest) and earlier version 1.4, but getting the following traceback.  Perhaps recent dependency upgrade broke something?

$ sops -d /tmp/my_config.xml.ENC > config.xml
 Traceback (most recent call last):
   File "/usr/local/bin//sops", line 9, in <module>
     load_entry_point('sops==1.4', 'console_scripts', 'sops')()
   File "/usr/local/lib/python2.7/dist-packages/sops/__init__.py", line 218, in main
     tree = walk_and_decrypt(tree, key, ignoreMac=args.ignore_mac)
   File "/usr/local/lib/python2.7/dist-packages/sops/__init__.py", line 641, in walk_and_decrypt
     branch[k] = decrypt(v, key, aad=caad, stash=nstash, digest=digest)
   File "/usr/local/lib/python2.7/dist-packages/sops/__init__.py", line 698, in decrypt
     default_backend()
   File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
     _default_backend = MultiBackend(_available_backends())
   File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
     "cryptography.backends"
 AttributeError: 'EntryPoint' object has no attribute 'resolve'

**Comment by rpappalax** [comment]
hmm, looks like you have most versions already pinned in requirements.txt so not sure what's going on here.

**Comment by jvehent** [comment]
Let me guess: You're on OSX El Capitan? -> https://github.com/pyca/cryptography/issues/2838

**Comment by rpappalax** [comment]
Ubuntu linux

**Comment by jvehent** [comment]
Odd. Try downgrading cryptography maybe? `pip install cryptography==1.2.1`

**Comment by rpappalax** [comment]
Yep, downgrading to cryptography 1.2.1 fixed it.  Thank you!
