### ISSUE TITLE
I get "panic: impossible" trying to do a "sops -d" with GPG keys

### ISSUE THREAD

**Issue by eswenson1** [mozilla/sops#807]
I'm able to do a "sops -e secret-clear.yaml > secret.yaml" fine with SOPS 3.6.1.  But when I attempt to do a "sops -d secret.yaml > foo.yaml", I get a "panic: impossible" error with a stack trace.  The stack trace begins like this:

```sops -d secret.yaml
panic: impossible

goroutine 1 [running]:
golang.org/x/crypto/openpgp/packet.(*PrivateKey).parsePrivateKey(0xc000506d00, 0xc000524600, 0x24, 0x600, 0x24, 0x600)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550/openpgp/packet/private_key.go:293 +0x18f
golang.org/x/crypto/openpgp/packet.(*PrivateKey).parse(0xc000506d00, 0x1e12940, 0xc000501320, 0x7b, 0x1e12940)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550/openpgp/packet/private_key.go:142 +0x24f
golang.org/x/crypto/openpgp/packet.Read(0x1e13760, 0xc0001b0468, 0x0, 0x0, 0x1e14520, 0x23ad200)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550/openpgp/packet/packet.go:375 +0x159
golang.org/x/crypto/openpgp/packet.(*Reader).Next(0xc00035da18, 0x1e12820, 0xc0001f7880, 0x0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550/openpgp/packet/reader.go:37 +0x6d
golang.org/x/crypto/openpgp.readToNextPublicKey(0xc00035da18, 0x0, 0x1e14540)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550/openpgp/keys.go:294 +0x2f
golang.org/x/crypto/openpgp.ReadKeyRing(0x1e13760, 0xc0001b0468, 0x0, 0x0, 0xc0001b0468, 0x0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550/openpgp/keys.go:264 +0x13a
go.mozilla.org/sops/v3/pgp.(*MasterKey).loadRing(0xc0004c3bc0, 0xc0002407e0, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/pgp/keysource.go:288 +0xb7
go.mozilla.org/sops/v3/pgp.(*MasterKey).secRing(0xc0004c3bc0, 0x100f910, 0xc0004c3bc0, 0x40, 0x38, 0x1bc6b40)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/pgp/keysource.go:296 +0x73
go.mozilla.org/sops/v3/pgp.(*MasterKey).decryptWithCryptoOpenpgp(0xc0004c3bc0, 0x1010278, 0x40, 0x1bc6b40, 0x1c402d01, 0x10000c0004c3bc0)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/pgp/keysource.go:204 +0x45
go.mozilla.org/sops/v3/pgp.(*MasterKey).Decrypt(0xc0004c3bc0, 0xc0002be6c0, 0x234, 0xc0002be900, 0x234, 0x2689e98)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/pgp/keysource.go:224 +0x45
go.mozilla.org/sops/v3/keyservice.(*Server).decryptWithPgp(0xc00035ddd8, 0xc0004d6c00, 0xc0002be6c0, 0x234, 0x240, 0x203000, 0x0, 0x240, 0x203000, 0x203000)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/keyservice/server.go:81 +0x8f
go.mozilla.org/sops/v3/keyservice.Server.Decrypt(0x1850f00, 0x1e299c0, 0xc0001b4010, 0xc0004c3b80, 0x1bed7c0, 0x201, 0xc0004c3b80)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/keyservice/server.go:225 +0x51d
go.mozilla.org/sops/v3/keyservice.LocalClient.Decrypt(...)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/keyservice/client.go:23
go.mozilla.org/sops/v3.decryptKey(0x1e32ca0, 0xc0004c3980, 0xc0004c5040, 0x1, 0x1, 0x23f8100, 0x0, 0x11040a2, 0xc000000031, 0x104e200)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/sops.go:693 +0x402
go.mozilla.org/sops/v3.decryptKeyGroup(0xc0004c3a40, 0x4, 0x4, 0xc0004c5040, 0x1, 0x1, 0xc00035e160, 0x188b5e8, 0xc0004d27fc, 0x1, ...)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/sops.go:668 +0xce
go.mozilla.org/sops/v3.Metadata.GetDataKeyWithKeyServices(0x0, 0xed7a38b5c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0004d5b80, ...)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/sops.go:635 +0x185
go.mozilla.org/sops/v3/cmd/sops/common.DecryptTree(0xc0004ea000, 0xc0004c5040, 0x1, 0x1, 0x0, 0x1e1e140, 0xc0004d65d0, 0xc0004c5040, 0x1, 0x1, ...)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/cmd/sops/common/common.go:83 +0xaa
main.decrypt(0x1e1e140, 0xc0004d65d0, 0x359fa58, 0x2428628, 0x359fa58, 0x2428628, 0xc00018e840, 0x5a, 0x0, 0x0, ...)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/cmd/sops/decrypt.go:34 +0x1fb
main.main.func8(0xc00020f080, 0x0, 0x0)
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/cmd/sops/main.go:769 +0x2a05
gopkg.in/urfave/cli%2ev1.HandleAction(0x1ad0680, 0x1cc4f00, 0xc00020f080, 0x0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0003e5ba0, 0xc00019a180, 0x3, 0x3, 0x0, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
        /private/tmp/sops-20201115-66106-b57ufl/sops-3.6.1/cmd/sops/main.go:933 +0x3525
```

I have no trouble using "sops -e" to encrypt.

**Comment by autrilla** [comment]
It seems like a bug in the openpgp library. Not much we can do about it
unless they’ve already fixed it.

**Comment by eswenson1** [comment]
Thanks for the pointer.  I did the following (am am now able to use "sops -e" and "sops -d" with no errors:

* exported my public and private keys to files
* renamed my .gnupg directory to get it out of the way
* imported my public and private keys, as well as SOPS public keys for others -- this created a brand new .gnupg directory

My guess is that my old keyring (that I've had for 20+ years and has been upgraded over the years a few times) had some weirdness in it -- or a bad private key that the current gpg couldn't handle.
